### ISSUE TITLE
response status code always 0

### ISSUE THREAD

**Issue by tiberiu89** [devopsfaith/krakend-lua#25]
Hi,
I'm trying to check status code from backend response, always gives a 0, amI missing something?

```json
"backend": [
        {
          "url_pattern": "/rewarding/allowances",
          "encoding": "json",
          "sd": "static",
          "method": "GET",
          "extra_config": {
            "github.com/devopsfaith/krakend/http": {
              "return_error_details": "rewarding"
            },
            "github.com/devopsfaith/krakend-lua/proxy/backend": {
              "sources": ["scripts/error_handler.lua"],
              "post": "handle_error(response.load())",
              "live": true,
              "allow_open_libs": true
            }
          },
          "host": [
            "http://sf-rewarding:3000"
          ],
          "disable_host_sanitize": true
        }
      ]
```

```lua
function handle_error(resp)
  print(resp:statusCode())
  print(resp:data():get('data'):get(0):get('id'))
end
```

![image](https://user-images.githubusercontent.com/42996791/129360404-a92c8406-13fe-4f7c-825e-af0b8016f1b2.png)

**Comment by kpacha** [comment]
Regular pipes do not store the status code or the response headers. That's why you're getting a 0 when printing the status code.

If you want to pass the response as it was received, you need to use a `no-op` pipe. Keep in mind that in that scenario, the body is not decoded and it's accessible as a string using `resp:body()`
